name = "produccion-inteligente"
main = "index.ts"
compatibility_date = "2026-08-04"
workers_dev = true

[env.production]
name = "produccion-inteligente"
vars = { PROJECT_NAME = "Producción inteligente" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "produccion_inteligente_db"

[[env.production.r2_buckets]]
binding = "ASSETS"
bucket_name = "produccion-inteligente-assets"

[assets]
directory = "../frontend/dist"
binding = "ASSETS_FETCH"
